spring:
  security:
    jwt:
      secret: QmFzZTY0U2VjdXJlS2V5Rm9ySldUQXV0aGVudGljYXRpb24=
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      database-plataform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate.format_sql: true
server:
  port: 8080
logging:
  level:
    root: WARN
    org.springframework: INFO
    org.hibernate.SQL: DEBUG

