spring:
  security:
    jwt:
      secret: ${SPRING_SECURITY_JWT_SECRET}
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    show-sql: ${SPRING_JPA_SHOW_SQL}
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
      database-plataform: ${SPRING_JPA_DATABASE_PLATFORM}
    properties:
      hibernate.format_sql: ${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL}

server:
  port: ${SERVER_PORT}

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT}
    org.springframework: ${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK}
    org.hibernate.SQL: ${LOGGING_LEVEL_ORG_HIBERNATE_SQL}
