spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      database-plataform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate.format_sql: true
server:
  port: 8080


